#!/usr/bin/env python3
"""Generate index.md / index.zh-CN.md from per-skill metadata.

Single source of truth: the `<!-- index: ... -->` HTML comment in each
skills/<name>/SKILL.md, plus a short description from a table in this script
(bilingual). Skills without an index comment are a hard error — an unindexed
skill is invisible to the catalog.

Usage:
    python scripts/generate_index.py          # write both files
    python scripts/generate_index.py --check  # exit 1 on drift (CI)
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"

AREAS = ("software-development", "work-management", "self-management")
TARGETS = ("runtime-agnostic", "repo-only", "claude-code", "codex", "opencode",
           "hermes", "pi", "kimi-code")

# One-line notes per skill. Keep in sync with the SKILL.md description.
NOTES = {
    "ghc-search": (
        "web and X/Twitter search via a local ghc-proxy Responses API; answer plus deduped sources",
        "经本机 `ghc-proxy` Responses API 做 web 与 X/Twitter 搜索；返回答案加去重来源",
    ),
    "define-goal": (
        "define one cohesive, verifiable goal or the smallest sufficient goal set without planning implementation",
        "把意图定义为一个完整、可验证的目标或最小充分目标集，不制定实现方案",
    ),
    "git-worktree-workflow": (
        "run several agent CLIs in parallel on one repo via isolated worktrees; ships the `gitwt` helper",
        "用隔离的 worktree 在同一仓库并行运行多个 agent CLI；随附 `gitwt` 助手",
    ),
    "hoa-agent-retrieve": (
        "cross-agent history → coverage-manifested, deduped Retrieval Bundle",
        "跨 agent 历史 → 带 coverage manifest、已去重的 Retrieval Bundle",
    ),
    "hoa-introspect": (
        "layered self-report: deterministic usage facets (L1) + evidence-cited blind-spot audit (L2)",
        "分层自省报告：确定性使用 facets（L1）+ 带证据的盲点审计（L2）",
    ),
    "hoa-introspect-distill": (
        "distill approved repeatable work into a skill (or opt-in rule/config) via the runtime-native skill-creator or inline",
        "把已批准的可复用工作提炼成 skill（或 opt-in 的 rule/config），经 runtime 原生 skill-creator 或内联产出",
    ),
    "my-ado-cppr": (
        "commit → push → create/update PR on Azure DevOps or GitHub; probe/plan/apply with resumable state",
        "commit → push → 在 Azure DevOps 或 GitHub 创建/更新 PR；probe/plan/apply 三段式，状态可 resume",
    ),
}

INDEX_COMMENT = re.compile(
    r"^<!--\s*index:\s*(?P<kv>.*)\s*-->\s*$", re.MULTILINE
)
KV = re.compile(r"(\w+)\s*=\s*([^;]+)")


def parse_metadata(skill_md: Path) -> dict[str, str]:
    text = skill_md.read_text(encoding="utf-8")
    m = INDEX_COMMENT.search(text)
    if not m:
        raise ValueError(f"no `<!-- index: ... -->` comment in {skill_md}")
    meta = {k: v.strip() for k, v in KV.findall(m.group("kv"))}
    for key in ("areas", "targets"):
        if key not in meta:
            raise ValueError(f"missing `{key}=` in {skill_md}")
    for a in meta["areas"].split(","):
        if a.strip() not in AREAS:
            raise ValueError(f"unknown area {a!r} in {skill_md}")
    for t in meta["targets"].split(","):
        if t.strip() not in TARGETS:
            raise ValueError(f"unknown target {t!r} in {skill_md}")
    return meta


def collect() -> list[dict]:
    rows = []
    for skill_md in sorted(SKILLS.glob("*/SKILL.md")):
        name = skill_md.parent.name
        meta = parse_metadata(skill_md)
        if name not in NOTES:
            raise ValueError(f"no catalog note for skill {name!r} in NOTES")
        rows.append({"name": name, **meta})
    if not rows:
        raise ValueError("no skills found")
    return rows


HEADER_EN = """# Index — artifacts by area & target

> **English** · [简体中文](./index.zh-CN.md)

The repo is organized **by type** (the folders). Every logical artifact also
gets **one row here**, labeled by `areas` and `targets` — because one artifact
often serves several areas or runtimes, and folders can't express that.

> Generated by `python scripts/generate_index.py` — never edit the catalog
> table by hand; edit each skill's `<!-- index: ... -->` comment instead.

## Label vocabulary

```text
areas:    software-development | work-management | self-management
targets:  runtime-agnostic | repo-only |
          claude-code | codex | opencode | hermes | pi | kimi-code
```

- Both axes are **multi-valued** (comma-separated).
- **Type** is derived from the top-level folder — don't re-label it.
- `targets` = which `npx skills --agent` a skill installs to (`runtime-agnostic`
  = any; `repo-only` = never deployed, e.g. library/knowledge types).
- One row per **logical** artifact (not one per bilingual file).
- No `status` axis until experimental / deprecated states actually appear.

## Catalog

| Artifact | Type | Areas | Targets | Path | Notes |
|---|---|---|---|---|---|
"""

FOOTER_EN = """
> Non-skill types (orchestration · agent · workflow · mcp · prompt · rule · eval · reflection) populate as real artifacts land.
"""

HEADER_ZH = """# Index — 按 area 与 target 索引

> [English](./index.md) · **简体中文**

仓库**按类型**组织（就是那些目录）。每个逻辑 artifact 在这里也占**一行**，用
`areas` 和 `targets` 打标签——因为一个 artifact 常同时服务多个 area 或 runtime，
而目录表达不了这一点。

> 由 `python scripts/generate_index.py` 生成——目录表不要手改；改每个 skill 里的
> `<!-- index: ... -->` 注释即可。

## 标签词表

```text
areas:    software-development | work-management | self-management
targets:  runtime-agnostic | repo-only |
          claude-code | codex | opencode | hermes | pi | kimi-code
```

- 两个轴都**可多值**（逗号分隔）。
- **type** 从顶层目录推导——不要重复打标。
- `targets` = 这个 skill 用 `npx skills --agent` 装到哪些 runtime
  （`runtime-agnostic` = 任意；`repo-only` = 永不下发，如库 / 知识类）。
- 一行对应一个**逻辑** artifact（不为双语文件分别建行）。
- 暂不设 `status` 轴，等实验 / 废弃状态真的出现再加。

## 编目

| Artifact | Type | Areas | Targets | Path | Notes |
|---|---|---|---|---|---|
"""

FOOTER_ZH = """
> 非 skill 类型（orchestration · agent · workflow · mcp · prompt · rule · eval · reflection）会在真实 artifact 落地时补充。
"""


def render(rows: list[dict], lang: str) -> str:
    header, footer = (HEADER_EN, FOOTER_EN) if lang == "en" else (HEADER_ZH, FOOTER_ZH)
    note_i = 0 if lang == "en" else 1
    out = [header]
    for r in rows:  # collect() already sorted by name
        note = NOTES[r["name"]][note_i]
        out.append(
            f"| {r['name']} | skill | {r['areas']} | {r['targets']} | "
            f"`skills/{r['name']}/` | {note} |\n"
        )
    out.append(footer)
    return "".join(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify generated files are up to date; exit 1 on drift")
    args = ap.parse_args(argv)

    try:
        rows = collect()
    except ValueError as e:
        print(f"generate_index: {e}", file=sys.stderr)
        return 1

    status = 0
    for lang, filename in (("en", "index.md"), ("zh", "index.zh-CN.md")):
        content = render(rows, lang)
        target = ROOT / filename
        if args.check:
            if target.read_text(encoding="utf-8") != content:
                print(f"generate_index: {filename} is stale; run "
                      f"python scripts/generate_index.py", file=sys.stderr)
                status = 1
        else:
            target.write_text(content, encoding="utf-8")
            print(f"wrote {filename} ({len(rows)} artifacts)")
    return status


if __name__ == "__main__":
    sys.exit(main())
